jenkins:
  systemMessage: "Welcome to Jenkins configured via Code!"
  securityRealm:
    local:
      allowsSignup: false
      users:
      - id: "admin"
        password: "admin_password"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  disableRememberMe: true
  numExecutors: 2
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true


unclassified:
  location:
    url: "http://localhost:8080/"